// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCow9o2oeId4vboS5tuQP8bMeaTRanbPIk',
    appId: '1:533097576818:web:d7cbb1fdd8be153e4e85eb',
    messagingSenderId: '533097576818',
    projectId: 'wins-eb2da',
    authDomain: 'wins-eb2da.firebaseapp.com',
    storageBucket: 'wins-eb2da.firebasestorage.app',
    measurementId: 'G-SSC6R86G89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-QgmAI4uccUWbzbm437CX8188zNvb_Js',
    appId: '1:533097576818:android:e22902e93f0667c94e85eb',
    messagingSenderId: '533097576818',
    projectId: 'wins-eb2da',
    storageBucket: 'wins-eb2da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr-kK5Y8P0t21AFhrUyedJPsgSOmZdPMw',
    appId: '1:533097576818:ios:74cb3d77932273764e85eb',
    messagingSenderId: '533097576818',
    projectId: 'wins-eb2da',
    storageBucket: 'wins-eb2da.firebasestorage.app',
    iosBundleId: 'com.example.winsEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr-kK5Y8P0t21AFhrUyedJPsgSOmZdPMw',
    appId: '1:533097576818:ios:74cb3d77932273764e85eb',
    messagingSenderId: '533097576818',
    projectId: 'wins-eb2da',
    storageBucket: 'wins-eb2da.firebasestorage.app',
    iosBundleId: 'com.example.winsEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCow9o2oeId4vboS5tuQP8bMeaTRanbPIk',
    appId: '1:533097576818:web:79218ed527ac65134e85eb',
    messagingSenderId: '533097576818',
    projectId: 'wins-eb2da',
    authDomain: 'wins-eb2da.firebaseapp.com',
    storageBucket: 'wins-eb2da.firebasestorage.app',
    measurementId: 'G-R1NVHM0E7K',
  );
}
